// Extended Mock Data for all new content modules
import type {
  CMSExam,
  CMSResult,
  CMSInstitution,
  CMSHoliday,
  CMSRestaurant,
  CMSFashionStore,
  CMSShoppingCentre,
  CMSFamousPlace,
  CMSEvent,
} from './extendedTypes';

// ============ EDUCATION: EXAMS ============
export const mockExams: CMSExam[] = [
  {
    id: 'exam-1',
    title: 'UP Board Class 10 Exam 2026',
    titleHindi: 'यूपी बोर्ड कक्षा 10 परीक्षा 2026',
    slug: 'up-board-class-10-exam-2026',
    examDate: '2026-02-20',
    applicationStartDate: '2025-09-01',
    applicationEndDate: '2025-10-31',
    resultDate: '2026-05-15',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'उत्तर प्रदेश बोर्ड की कक्षा 10 वार्षिक परीक्षा',
    status: 'upcoming',
    isPopular: true,
  },
  {
    id: 'exam-2',
    title: 'UP Board Class 12 Exam 2026',
    titleHindi: 'यूपी बोर्ड कक्षा 12 परीक्षा 2026',
    slug: 'up-board-class-12-exam-2026',
    examDate: '2026-02-25',
    applicationStartDate: '2025-09-01',
    applicationEndDate: '2025-10-31',
    resultDate: '2026-05-20',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'उत्तर प्रदेश बोर्ड की कक्षा 12 वार्षिक परीक्षा',
    status: 'upcoming',
    isPopular: true,
  },
  {
    id: 'exam-3',
    title: 'UPTET 2026',
    titleHindi: 'यूपीटीईटी 2026',
    slug: 'uptet-2026',
    examDate: '2026-01-20',
    applicationStartDate: '2025-10-15',
    applicationEndDate: '2025-11-15',
    organization: 'UP Basic Education Board',
    organizationHindi: 'उत्तर प्रदेश बेसिक शिक्षा परिषद',
    category: 'government',
    description: 'उत्तर प्रदेश शिक्षक पात्रता परीक्षा',
    status: 'upcoming',
    isPopular: true,
  },
  {
    id: 'exam-4',
    title: 'UP Police Constable Exam 2026',
    titleHindi: 'यूपी पुलिस कांस्टेबल भर्ती परीक्षा 2026',
    slug: 'up-police-constable-2026',
    examDate: '2026-03-10',
    organization: 'UP Police Recruitment Board',
    organizationHindi: 'उत्तर प्रदेश पुलिस भर्ती बोर्ड',
    category: 'government',
    description: 'उत्तर प्रदेश पुलिस कांस्टेबल पद हेतु भर्ती परीक्षा',
    status: 'upcoming',
    isPopular: true,
  },
  {
    id: 'exam-5',
    title: 'AMU Entrance Exam 2026',
    titleHindi: 'एएमयू प्रवेश परीक्षा 2026',
    slug: 'amu-entrance-2026',
    examDate: '2026-04-15',
    organization: 'Aligarh Muslim University',
    organizationHindi: 'अलीगढ़ मुस्लिम विश्वविद्यालय',
    category: 'entrance',
    description: 'अलीगढ़ मुस्लिम विश्वविद्यालय प्रवेश परीक्षा',
    status: 'upcoming',
    isPopular: true,
  },
];

// ============ EDUCATION: RESULTS ============
export const mockResults: CMSResult[] = [
  {
    id: 'result-1',
    title: 'UP Board Class 10 Result 2025',
    titleHindi: 'यूपी बोर्ड कक्षा 10 परिणाम 2025',
    slug: 'up-board-class-10-result-2025',
    resultDate: '2025-05-15',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'यूपी बोर्ड कक्षा 10 का परिणाम घोषित',
    resultLink: 'https://upresults.nic.in',
    totalCandidates: 2500000,
    passPercentage: 87.5,
  },
  {
    id: 'result-2',
    title: 'UP Board Class 12 Result 2025',
    titleHindi: 'यूपी बोर्ड कक्षा 12 परिणाम 2025',
    slug: 'up-board-class-12-result-2025',
    resultDate: '2025-05-20',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'यूपी बोर्ड कक्षा 12 का परिणाम घोषित',
    resultLink: 'https://upresults.nic.in',
    totalCandidates: 2200000,
    passPercentage: 82.3,
  },
  {
    id: 'result-3',
    title: 'UPTET 2025 Result',
    titleHindi: 'यूपीटीईटी 2025 परिणाम',
    slug: 'uptet-2025-result',
    resultDate: '2025-03-10',
    organization: 'UP Basic Education Board',
    organizationHindi: 'उत्तर प्रदेश बेसिक शिक्षा परिषद',
    category: 'government',
    description: 'यूपीटीईटी 2025 का परिणाम घोषित',
    resultLink: 'https://updeled.gov.in',
    totalCandidates: 1500000,
    passPercentage: 25.8,
  },
];

// ============ EDUCATION: INSTITUTIONS ============
export const mockInstitutions: CMSInstitution[] = [
  {
    id: 'inst-1',
    name: 'Government Inter College, Rampur',
    nameHindi: 'राजकीय इंटर कॉलेज, रामपुर',
    slug: 'government-inter-college-rampur',
    type: 'college',
    address: 'Civil Lines, Rampur',
    addressHindi: 'सिविल लाइंस, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    pincode: '244901',
    phone: '0595-2350001',
    establishedYear: 1925,
    affiliation: 'UP Board',
    courses: ['Arts', 'Science', 'Commerce'],
    facilities: ['Library', 'Sports Ground', 'Computer Lab'],
    rating: 4.2,
    reviews: 156,
    description: 'One of the oldest and most prestigious inter colleges in Rampur district.',
    descriptionHindi: 'रामपुर जिले के सबसे पुराने और प्रतिष्ठित इंटर कॉलेजों में से एक।',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: 'inst-2',
    name: 'Rampur Public School',
    nameHindi: 'रामपुर पब्लिक स्कूल',
    slug: 'rampur-public-school',
    type: 'school',
    address: 'Naya Ganj, Rampur',
    addressHindi: 'नया गंज, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    pincode: '244901',
    phone: '0595-2350002',
    establishedYear: 1985,
    affiliation: 'CBSE',
    courses: ['Primary', 'Secondary', 'Senior Secondary'],
    facilities: ['Smart Classes', 'Library', 'Sports Complex', 'Science Labs'],
    rating: 4.5,
    reviews: 234,
    description: 'A leading CBSE affiliated school in Rampur.',
    descriptionHindi: 'रामपुर का एक प्रमुख सीबीएसई संबद्ध विद्यालय।',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: 'inst-3',
    name: 'MJP Rohilkhand University',
    nameHindi: 'एमजेपी रुहेलखंड विश्वविद्यालय',
    slug: 'mjp-rohilkhand-university',
    type: 'university',
    address: 'Bareilly',
    addressHindi: 'बरेली',
    city: 'बरेली',
    district: 'बरेली',
    pincode: '243006',
    phone: '0581-2527263',
    website: 'https://mjpru.ac.in',
    establishedYear: 1975,
    courses: ['B.A.', 'B.Sc.', 'B.Com.', 'M.A.', 'M.Sc.', 'Ph.D.'],
    facilities: ['Central Library', 'Hostels', 'Sports Complex', 'Research Centers'],
    rating: 4.0,
    reviews: 456,
    description: 'State university serving Rohilkhand region including Rampur.',
    descriptionHindi: 'रामपुर सहित रुहेलखंड क्षेत्र की सेवा करने वाला राज्य विश्वविद्यालय।',
    isVerified: true,
    isFeatured: true,
  },
];

// ============ CULTURE: HOLIDAYS ============
export const mockHolidays: CMSHoliday[] = [
  {
    id: 'holiday-1',
    name: 'Republic Day',
    nameHindi: 'गणतंत्र दिवस',
    slug: 'republic-day',
    date: '2026-01-26',
    type: 'national',
    description: 'India celebrates its Republic Day on January 26th.',
    descriptionHindi: 'भारत 26 जनवरी को अपना गणतंत्र दिवस मनाता है।',
    significance: 'The day India became a republic in 1950.',
    isRecurring: true,
    recurringType: 'yearly',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-2',
    name: 'Holi',
    nameHindi: 'होली',
    slug: 'holi',
    date: '2026-03-04',
    type: 'religious',
    religion: 'hindu',
    description: 'Festival of colors celebrating the victory of good over evil.',
    descriptionHindi: 'रंगों का त्योहार जो बुराई पर अच्छाई की जीत का जश्न मनाता है।',
    significance: 'Celebrates the divine love of Radha Krishna and victory of Prahlad.',
    rituals: ['Playing with colors', 'Holika Dahan', 'Gujiya preparation'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-3',
    name: 'Eid ul-Fitr',
    nameHindi: 'ईद उल-फ़ित्र',
    slug: 'eid-ul-fitr',
    date: '2026-03-21',
    type: 'religious',
    religion: 'muslim',
    description: 'Festival marking the end of Ramadan.',
    descriptionHindi: 'रमज़ान के समापन का पर्व।',
    significance: 'Celebrates the end of month-long fasting.',
    rituals: ['Eid prayers', 'Giving Zakat', 'Family gatherings', 'Feasting'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-4',
    name: 'Independence Day',
    nameHindi: 'स्वतंत्रता दिवस',
    slug: 'independence-day',
    date: '2026-08-15',
    type: 'national',
    description: 'India celebrates its independence from British rule.',
    descriptionHindi: 'भारत ब्रिटिश शासन से अपनी स्वतंत्रता का जश्न मनाता है।',
    significance: 'India gained independence on August 15, 1947.',
    isRecurring: true,
    recurringType: 'yearly',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-5',
    name: 'Diwali',
    nameHindi: 'दिवाली',
    slug: 'diwali',
    date: '2026-10-20',
    endDate: '2026-10-24',
    type: 'religious',
    religion: 'hindu',
    description: 'Festival of lights celebrating the victory of light over darkness.',
    descriptionHindi: 'रोशनी का त्योहार जो अंधकार पर प्रकाश की जीत का जश्न मनाता है।',
    significance: 'Celebrates Lord Rama\'s return to Ayodhya.',
    rituals: ['Lighting diyas', 'Lakshmi Puja', 'Fireworks', 'Rangoli'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-6',
    name: 'Eid ul-Adha',
    nameHindi: 'ईद उल-अज़हा',
    slug: 'eid-ul-adha',
    date: '2026-05-27',
    type: 'religious',
    religion: 'muslim',
    description: 'Festival of Sacrifice.',
    descriptionHindi: 'कुर्बानी का त्योहार।',
    significance: 'Commemorates Ibrahim\'s willingness to sacrifice his son.',
    rituals: ['Eid prayers', 'Qurbani', 'Charity', 'Family gatherings'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-7',
    name: 'Gandhi Jayanti',
    nameHindi: 'गांधी जयंती',
    slug: 'gandhi-jayanti',
    date: '2026-10-02',
    type: 'national',
    description: 'Birthday of Mahatma Gandhi.',
    descriptionHindi: 'महात्मा गांधी का जन्मदिन।',
    significance: 'Celebrates the Father of the Nation.',
    isRecurring: true,
    recurringType: 'yearly',
    isPublicHoliday: true,
  },
];

// ============ FOOD & LIFESTYLE: RESTAURANTS ============
export const mockRestaurants: CMSRestaurant[] = [
  {
    id: 'rest-1',
    name: 'Sharma Ji Ka Dhaba',
    nameHindi: 'शर्मा जी का ढाबा',
    slug: 'sharma-ji-ka-dhaba',
    type: 'dhaba',
    cuisine: ['North Indian', 'Mughlai'],
    address: 'Civil Lines, Rampur',
    addressHindi: 'सिविल लाइंस, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543210',
    priceRange: 'budget',
    rating: 4.3,
    reviews: 234,
    openingHours: '7:00 AM - 11:00 PM',
    specialties: ['Dal Makhani', 'Butter Chicken', 'Tandoori Roti'],
    description: 'Famous dhaba known for authentic North Indian cuisine.',
    descriptionHindi: 'प्रामाणिक उत्तर भारतीय व्यंजनों के लिए प्रसिद्ध ढाबा।',
    isVeg: false,
    hasDelivery: true,
    isFeatured: true,
  },
  {
    id: 'rest-2',
    name: 'Rampur Sweet House',
    nameHindi: 'रामपुर स्वीट हाउस',
    slug: 'rampur-sweet-house',
    type: 'sweet-shop',
    cuisine: ['Sweets', 'Snacks'],
    address: 'Naya Ganj, Rampur',
    addressHindi: 'नया गंज, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543211',
    priceRange: 'moderate',
    rating: 4.6,
    reviews: 456,
    openingHours: '8:00 AM - 10:00 PM',
    specialties: ['Gulab Jamun', 'Jalebi', 'Samosa', 'Kachori'],
    description: 'Traditional sweet shop serving authentic Rampur sweets.',
    descriptionHindi: 'पारंपरिक मिठाई की दुकान जो प्रामाणिक रामपुरी मिठाइयाँ परोसती है।',
    isVeg: true,
    hasDelivery: true,
    isFeatured: true,
  },
  {
    id: 'rest-3',
    name: 'Royal Biryani House',
    nameHindi: 'रॉयल बिरयानी हाउस',
    slug: 'royal-biryani-house',
    type: 'restaurant',
    cuisine: ['Mughlai', 'Biryani'],
    address: 'Shahbad Gate, Rampur',
    addressHindi: 'शाहबाद गेट, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543212',
    priceRange: 'moderate',
    rating: 4.4,
    reviews: 312,
    openingHours: '11:00 AM - 11:00 PM',
    specialties: ['Mutton Biryani', 'Chicken Biryani', 'Kebabs'],
    description: 'Famous for Nawabi style biryani and kebabs.',
    descriptionHindi: 'नवाबी स्टाइल बिरयानी और कबाब के लिए प्रसिद्ध।',
    isVeg: false,
    hasDelivery: true,
    isFeatured: true,
  },
];

// ============ FOOD & LIFESTYLE: FASHION STORES ============
export const mockFashionStores: CMSFashionStore[] = [
  {
    id: 'fashion-1',
    name: 'Rampur Saree Emporium',
    nameHindi: 'रामपुर साड़ी एम्पोरियम',
    slug: 'rampur-saree-emporium',
    type: 'clothing',
    category: 'women',
    address: 'Main Market, Rampur',
    addressHindi: 'मुख्य बाजार, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543220',
    priceRange: 'moderate',
    rating: 4.5,
    specialties: ['Banarasi Sarees', 'Chikankari', 'Bridal Collection'],
    description: 'Premium saree collection for all occasions.',
    descriptionHindi: 'सभी अवसरों के लिए प्रीमियम साड़ी संग्रह।',
    isFeatured: true,
  },
  {
    id: 'fashion-2',
    name: 'Style Junction',
    nameHindi: 'स्टाइल जंक्शन',
    slug: 'style-junction',
    type: 'clothing',
    category: 'all',
    address: 'Civil Lines, Rampur',
    addressHindi: 'सिविल लाइंस, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543221',
    priceRange: 'moderate',
    rating: 4.2,
    brands: ['Van Heusen', 'Peter England', 'Allen Solly'],
    description: 'Branded clothing for men and women.',
    descriptionHindi: 'पुरुषों और महिलाओं के लिए ब्रांडेड कपड़े।',
    isFeatured: true,
  },
];

// ============ FOOD & LIFESTYLE: SHOPPING CENTRES ============
export const mockShoppingCentres: CMSShoppingCentre[] = [
  {
    id: 'shop-1',
    name: 'Rampur City Mall',
    nameHindi: 'रामपुर सिटी मॉल',
    slug: 'rampur-city-mall',
    type: 'mall',
    address: 'Bareilly Road, Rampur',
    addressHindi: 'बरेली रोड, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '0595-2350100',
    openingHours: '10:00 AM - 10:00 PM',
    storeCount: 50,
    amenities: ['Food Court', 'Cinema', 'Parking', 'Kids Zone'],
    parkingAvailable: true,
    description: 'Modern shopping mall with entertainment facilities.',
    descriptionHindi: 'मनोरंजन सुविधाओं के साथ आधुनिक शॉपिंग मॉल।',
    isFeatured: true,
  },
  {
    id: 'shop-2',
    name: 'Naya Ganj Market',
    nameHindi: 'नया गंज मार्केट',
    slug: 'naya-ganj-market',
    type: 'bazaar',
    address: 'Naya Ganj, Rampur',
    addressHindi: 'नया गंज, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    openingHours: '10:00 AM - 9:00 PM',
    description: 'Traditional market for daily shopping needs.',
    descriptionHindi: 'दैनिक खरीदारी की जरूरतों के लिए पारंपरिक बाजार।',
    isFeatured: true,
  },
];

// ============ FOOD & LIFESTYLE: FAMOUS PLACES ============
export const mockFamousPlaces: CMSFamousPlace[] = [
  {
    id: 'place-1',
    name: 'Rampur Raza Library',
    nameHindi: 'रामपुर रज़ा पुस्तकालय',
    slug: 'rampur-raza-library',
    type: 'historical',
    address: 'Fort Road, Rampur',
    addressHindi: 'किला रोड, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    description: 'One of the largest libraries in Asia with rare manuscripts.',
    descriptionHindi: 'दुर्लभ पांडुलिपियों के साथ एशिया की सबसे बड़ी पुस्तकालयों में से एक।',
    history: 'Established by Nawab Faizullah Khan in 1774.',
    timings: '10:00 AM - 5:00 PM',
    entryFee: 'Free',
    bestTimeToVisit: 'October to March',
    isFeatured: true,
    rating: 4.7,
  },
  {
    id: 'place-2',
    name: 'Jama Masjid Rampur',
    nameHindi: 'जामा मस्जिद रामपुर',
    slug: 'jama-masjid-rampur',
    type: 'religious',
    address: 'Old City, Rampur',
    addressHindi: 'पुराना शहर, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    description: 'Historic mosque built during Nawabi era.',
    descriptionHindi: 'नवाबी युग में निर्मित ऐतिहासिक मस्जिद।',
    history: 'Built in the 18th century by Nawabs of Rampur.',
    isFeatured: true,
    rating: 4.5,
  },
];

// ============ EVENTS ============
export const mockEvents: CMSEvent[] = [
  {
    id: 'event-1',
    title: 'Rampur Food Festival 2026',
    titleHindi: 'रामपुर फूड फेस्टिवल 2026',
    slug: 'rampur-food-festival-2026',
    date: '2026-02-15',
    endDate: '2026-02-17',
    time: '11:00 AM - 10:00 PM',
    venue: 'Rampur City Mall Grounds',
    venueHindi: 'रामपुर सिटी मॉल ग्राउंड्स',
    address: 'Bareilly Road, Rampur',
    city: 'रामपुर',
    district: 'रामपुर',
    category: 'food',
    organizer: 'Rampur Tourism',
    organizerHindi: 'रामपुर पर्यटन',
    description: 'Annual food festival showcasing local cuisine.',
    descriptionHindi: 'स्थानीय व्यंजनों का प्रदर्शन करने वाला वार्षिक खाद्य उत्सव।',
    ticketPrice: '₹100',
    isFree: false,
    isFeatured: true,
    status: 'upcoming',
  },
  {
    id: 'event-2',
    title: 'Cultural Night - Rampur Utsav',
    titleHindi: 'सांस्कृतिक संध्या - रामपुर उत्सव',
    slug: 'rampur-utsav-2026',
    date: '2026-03-10',
    time: '6:00 PM - 11:00 PM',
    venue: 'Town Hall',
    venueHindi: 'टाउन हॉल',
    address: 'Civil Lines, Rampur',
    city: 'रामपुर',
    district: 'रामपुर',
    category: 'cultural',
    organizer: 'District Administration',
    organizerHindi: 'जिला प्रशासन',
    description: 'Cultural evening with music, dance, and poetry.',
    descriptionHindi: 'संगीत, नृत्य और कविता के साथ सांस्कृतिक संध्या।',
    isFree: true,
    isFeatured: true,
    status: 'upcoming',
  },
  {
    id: 'event-3',
    title: 'Job Fair 2026',
    titleHindi: 'रोजगार मेला 2026',
    slug: 'job-fair-2026',
    date: '2026-01-25',
    time: '10:00 AM - 5:00 PM',
    venue: 'Government Inter College',
    venueHindi: 'राजकीय इंटर कॉलेज',
    address: 'Civil Lines, Rampur',
    city: 'रामपुर',
    district: 'रामपुर',
    category: 'educational',
    organizer: 'Employment Exchange',
    organizerHindi: 'रोजगार कार्यालय',
    description: 'Job fair for unemployed youth with 50+ companies.',
    descriptionHindi: 'बेरोजगार युवाओं के लिए 50+ कंपनियों के साथ रोजगार मेला।',
    isFree: true,
    isFeatured: true,
    status: 'upcoming',
  },
];
