// Extended Mock Data for all new content modules
import type {
  CMSExam,
  CMSResult,
  CMSInstitution,
  CMSHoliday,
  CMSRestaurant,
  CMSFashionStore,
  CMSShoppingCentre,
  CMSFamousPlace,
  CMSEvent,
  CMSCareerGuide,
  CMSEducationNews,
  CMSEducationEvent,
  CMSTestimonial,
  CMSExpert,
  CMSVideoTutorial,
} from './extendedTypes';

// ============ EDUCATION: EXAMS ============
export const mockExams: CMSExam[] = [
  {
    id: 'exam-1',
    title: 'UP Board Class 10 Exam 2026',
    titleHindi: 'यूपी बोर्ड कक्षा 10 परीक्षा 2026',
    slug: 'up-board-class-10-exam-2026',
    examDate: '2026-02-20',
    applicationStartDate: '2025-09-01',
    applicationEndDate: '2025-10-31',
    admitCardDate: '2026-02-01',
    resultDate: '2026-05-15',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'उत्तर प्रदेश बोर्ड की कक्षा 10 वार्षिक परीक्षा',
    descriptionHindi: 'उत्तर प्रदेश बोर्ड की कक्षा 10 वार्षिक परीक्षा - लाखों छात्रों के लिए महत्वपूर्ण',
    status: 'upcoming',
    applicationStatus: 'closed',
    admitCardStatus: 'upcoming',
    resultStatus: 'not-declared',
    isPopular: true,
    isFeatured: true,
    isNew: true,
    totalPosts: 2500000,
    officialWebsite: 'https://upmsp.edu.in',
  },
  {
    id: 'exam-2',
    title: 'UP Board Class 12 Exam 2026',
    titleHindi: 'यूपी बोर्ड कक्षा 12 परीक्षा 2026',
    slug: 'up-board-class-12-exam-2026',
    examDate: '2026-02-25',
    applicationStartDate: '2025-09-01',
    applicationEndDate: '2025-10-31',
    admitCardDate: '2026-02-05',
    resultDate: '2026-05-20',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'उत्तर प्रदेश बोर्ड की कक्षा 12 वार्षिक परीक्षा',
    descriptionHindi: 'उत्तर प्रदेश बोर्ड की कक्षा 12 वार्षिक परीक्षा',
    status: 'upcoming',
    applicationStatus: 'closed',
    admitCardStatus: 'upcoming',
    resultStatus: 'not-declared',
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'exam-3',
    title: 'UPTET 2026',
    titleHindi: 'यूपीटीईटी 2026',
    slug: 'uptet-2026',
    examDate: '2026-01-20',
    applicationStartDate: '2025-10-15',
    applicationEndDate: '2025-11-15',
    admitCardDate: '2026-01-10',
    organization: 'UP Basic Education Board',
    organizationHindi: 'उत्तर प्रदेश बेसिक शिक्षा परिषद',
    category: 'government',
    description: 'उत्तर प्रदेश शिक्षक पात्रता परीक्षा',
    descriptionHindi: 'उत्तर प्रदेश शिक्षक पात्रता परीक्षा - प्राथमिक और उच्च प्राथमिक शिक्षक बनने हेतु',
    status: 'upcoming',
    applicationStatus: 'open',
    admitCardStatus: 'not-released',
    resultStatus: 'not-declared',
    isPopular: true,
    isLive: true,
    totalPosts: 68500,
  },
  {
    id: 'exam-4',
    title: 'UP Police Constable Exam 2026',
    titleHindi: 'यूपी पुलिस कांस्टेबल भर्ती परीक्षा 2026',
    slug: 'up-police-constable-2026',
    examDate: '2026-03-10',
    applicationStartDate: '2025-12-01',
    applicationEndDate: '2025-12-31',
    organization: 'UP Police Recruitment Board',
    organizationHindi: 'उत्तर प्रदेश पुलिस भर्ती बोर्ड',
    category: 'government',
    description: 'उत्तर प्रदेश पुलिस कांस्टेबल पद हेतु भर्ती परीक्षा',
    descriptionHindi: 'उत्तर प्रदेश पुलिस कांस्टेबल पद हेतु भर्ती परीक्षा - 52000 पदों पर भर्ती',
    status: 'upcoming',
    applicationStatus: 'upcoming',
    admitCardStatus: 'not-released',
    resultStatus: 'not-declared',
    isPopular: true,
    totalPosts: 52000,
  },
  {
    id: 'exam-5',
    title: 'AMU Entrance Exam 2026',
    titleHindi: 'एएमयू प्रवेश परीक्षा 2026',
    slug: 'amu-entrance-2026',
    examDate: '2026-04-15',
    applicationStartDate: '2026-01-01',
    applicationEndDate: '2026-02-28',
    organization: 'Aligarh Muslim University',
    organizationHindi: 'अलीगढ़ मुस्लिम विश्वविद्यालय',
    category: 'entrance',
    description: 'अलीगढ़ मुस्लिम विश्वविद्यालय प्रवेश परीक्षा',
    status: 'upcoming',
    applicationStatus: 'upcoming',
    admitCardStatus: 'not-released',
    resultStatus: 'not-declared',
    isPopular: true,
  },
  {
    id: 'exam-6',
    title: 'UP Lekhpal Exam 2026',
    titleHindi: 'यूपी लेखपाल परीक्षा 2026',
    slug: 'up-lekhpal-2026',
    examDate: '2026-04-01',
    applicationStartDate: '2025-11-01',
    applicationEndDate: '2025-12-15',
    organization: 'UPSSSC',
    organizationHindi: 'उत्तर प्रदेश अधीनस्थ सेवा चयन आयोग',
    category: 'government',
    description: 'उत्तर प्रदेश लेखपाल भर्ती परीक्षा',
    status: 'upcoming',
    applicationStatus: 'open',
    admitCardStatus: 'not-released',
    resultStatus: 'not-declared',
    isPopular: true,
    isNew: true,
    totalPosts: 8085,
  },
  {
    id: 'exam-7',
    title: 'CTET January 2026',
    titleHindi: 'सीटीईटी जनवरी 2026',
    slug: 'ctet-january-2026',
    examDate: '2026-01-25',
    applicationStartDate: '2025-10-01',
    applicationEndDate: '2025-11-01',
    admitCardDate: '2026-01-15',
    organization: 'CBSE',
    organizationHindi: 'केंद्रीय माध्यमिक शिक्षा बोर्ड',
    category: 'government',
    description: 'Central Teacher Eligibility Test',
    descriptionHindi: 'केंद्रीय शिक्षक पात्रता परीक्षा - शिक्षक बनने हेतु अनिवार्य',
    status: 'upcoming',
    applicationStatus: 'closed',
    admitCardStatus: 'available',
    resultStatus: 'not-declared',
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'exam-8',
    title: 'SSC GD Constable 2026',
    titleHindi: 'एसएससी जीडी कांस्टेबल 2026',
    slug: 'ssc-gd-constable-2026',
    examDate: '2026-02-01',
    applicationStartDate: '2025-09-15',
    applicationEndDate: '2025-10-15',
    organization: 'Staff Selection Commission',
    organizationHindi: 'कर्मचारी चयन आयोग',
    category: 'government',
    description: 'SSC GD Constable Recruitment',
    descriptionHindi: 'एसएससी जीडी कांस्टेबल भर्ती - BSF, CISF, CRPF, SSB, ITBP पदों पर',
    status: 'upcoming',
    applicationStatus: 'closed',
    admitCardStatus: 'upcoming',
    resultStatus: 'not-declared',
    isPopular: true,
    totalPosts: 24369,
  },
];

// ============ EDUCATION: RESULTS ============
export const mockResults: CMSResult[] = [
  {
    id: 'result-1',
    title: 'UP Board Class 10 Result 2025',
    titleHindi: 'यूपी बोर्ड कक्षा 10 परिणाम 2025',
    slug: 'up-board-class-10-result-2025',
    resultDate: '2025-05-15',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'यूपी बोर्ड कक्षा 10 का परिणाम घोषित',
    descriptionHindi: 'यूपी बोर्ड कक्षा 10 का परिणाम घोषित - आधिकारिक वेबसाइट पर देखें',
    resultLink: 'https://upresults.nic.in',
    totalCandidates: 2500000,
    passPercentage: 87.5,
    status: 'declared',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'result-2',
    title: 'UP Board Class 12 Result 2025',
    titleHindi: 'यूपी बोर्ड कक्षा 12 परिणाम 2025',
    slug: 'up-board-class-12-result-2025',
    resultDate: '2025-05-20',
    organization: 'UP Board',
    organizationHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद',
    category: 'board',
    description: 'यूपी बोर्ड कक्षा 12 का परिणाम घोषित',
    resultLink: 'https://upresults.nic.in',
    totalCandidates: 2200000,
    passPercentage: 82.3,
    status: 'declared',
    isFeatured: true,
  },
  {
    id: 'result-3',
    title: 'UPTET 2025 Result',
    titleHindi: 'यूपीटीईटी 2025 परिणाम',
    slug: 'uptet-2025-result',
    resultDate: '2025-03-10',
    organization: 'UP Basic Education Board',
    organizationHindi: 'उत्तर प्रदेश बेसिक शिक्षा परिषद',
    category: 'government',
    description: 'यूपीटीईटी 2025 का परिणाम घोषित',
    resultLink: 'https://updeled.gov.in',
    totalCandidates: 1500000,
    passPercentage: 25.8,
    status: 'declared',
  },
  {
    id: 'result-4',
    title: 'UP Police SI Result 2025',
    titleHindi: 'यूपी पुलिस एसआई परिणाम 2025',
    slug: 'up-police-si-result-2025',
    resultDate: '2026-01-15',
    expectedDate: '2026-01-15',
    organization: 'UP Police Recruitment Board',
    organizationHindi: 'उत्तर प्रदेश पुलिस भर्ती बोर्ड',
    category: 'government',
    description: 'UP Police Sub Inspector Result Expected',
    status: 'expected',
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'result-5',
    title: 'CTET December 2025 Result',
    titleHindi: 'सीटीईटी दिसंबर 2025 परिणाम',
    slug: 'ctet-december-2025-result',
    resultDate: '2026-02-01',
    expectedDate: '2026-02-01',
    organization: 'CBSE',
    organizationHindi: 'केंद्रीय माध्यमिक शिक्षा बोर्ड',
    category: 'government',
    description: 'CTET December 2025 Result Expected',
    status: 'expected',
  },
];

// ============ EDUCATION: INSTITUTIONS ============
export const mockInstitutions: CMSInstitution[] = [
  {
    id: 'inst-1',
    name: 'Government Inter College, Rampur',
    nameHindi: 'राजकीय इंटर कॉलेज, रामपुर',
    slug: 'government-inter-college-rampur',
    type: 'college',
    address: 'Civil Lines, Rampur',
    addressHindi: 'सिविल लाइंस, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    state: 'उत्तर प्रदेश',
    pincode: '244901',
    phone: '0595-2350001',
    establishedYear: 1925,
    affiliation: 'UP Board',
    affiliationHindi: 'यूपी बोर्ड',
    courses: ['Arts', 'Science', 'Commerce'],
    coursesHindi: ['कला', 'विज्ञान', 'वाणिज्य'],
    facilities: ['Library', 'Sports Ground', 'Computer Lab'],
    facilitiesHindi: ['पुस्तकालय', 'खेल मैदान', 'कंप्यूटर लैब'],
    rating: 4.2,
    reviews: 156,
    description: 'One of the oldest and most prestigious inter colleges in Rampur district.',
    descriptionHindi: 'रामपुर जिले के सबसे पुराने और प्रतिष्ठित इंटर कॉलेजों में से एक।',
    about: 'Established in 1925, Government Inter College Rampur has been a cornerstone of education in the region.',
    aboutHindi: '1925 में स्थापित, राजकीय इंटर कॉलेज रामपुर क्षेत्र में शिक्षा की आधारशिला रहा है।',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: 'inst-2',
    name: 'Rampur Public School',
    nameHindi: 'रामपुर पब्लिक स्कूल',
    slug: 'rampur-public-school',
    type: 'school',
    address: 'Naya Ganj, Rampur',
    addressHindi: 'नया गंज, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    state: 'उत्तर प्रदेश',
    pincode: '244901',
    phone: '0595-2350002',
    establishedYear: 1985,
    affiliation: 'CBSE',
    affiliationHindi: 'सीबीएसई',
    courses: ['Primary', 'Secondary', 'Senior Secondary'],
    facilities: ['Smart Classes', 'Library', 'Sports Complex', 'Science Labs'],
    rating: 4.5,
    reviews: 234,
    description: 'A leading CBSE affiliated school in Rampur.',
    descriptionHindi: 'रामपुर का एक प्रमुख सीबीएसई संबद्ध विद्यालय।',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: 'inst-3',
    name: 'MJP Rohilkhand University',
    nameHindi: 'एमजेपी रुहेलखंड विश्वविद्यालय',
    slug: 'mjp-rohilkhand-university',
    type: 'university',
    address: 'Bareilly',
    addressHindi: 'बरेली',
    city: 'बरेली',
    district: 'बरेली',
    state: 'उत्तर प्रदेश',
    pincode: '243006',
    phone: '0581-2527263',
    website: 'https://mjpru.ac.in',
    establishedYear: 1975,
    courses: ['B.A.', 'B.Sc.', 'B.Com.', 'M.A.', 'M.Sc.', 'Ph.D.'],
    facilities: ['Central Library', 'Hostels', 'Sports Complex', 'Research Centers'],
    rating: 4.0,
    reviews: 456,
    description: 'State university serving Rohilkhand region including Rampur.',
    descriptionHindi: 'रामपुर सहित रुहेलखंड क्षेत्र की सेवा करने वाला राज्य विश्वविद्यालय।',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: 'inst-4',
    name: 'Apex Coaching Institute',
    nameHindi: 'एपेक्स कोचिंग इंस्टीट्यूट',
    slug: 'apex-coaching-institute',
    type: 'coaching',
    address: 'Near Bus Stand, Rampur',
    addressHindi: 'बस स्टैंड के पास, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    state: 'उत्तर प्रदेश',
    pincode: '244901',
    phone: '9876543210',
    establishedYear: 2010,
    courses: ['UPSC', 'SSC', 'Bank PO', 'Railway'],
    coursesHindi: ['यूपीएससी', 'एसएससी', 'बैंक पीओ', 'रेलवे'],
    facilities: ['AC Classrooms', 'Library', 'Mock Tests', 'Doubt Sessions'],
    rating: 4.3,
    reviews: 189,
    description: 'Leading coaching institute for competitive exams.',
    descriptionHindi: 'प्रतियोगी परीक्षाओं के लिए अग्रणी कोचिंग संस्थान।',
    isVerified: true,
    isFeatured: true,
  },
];

// ============ CAREER GUIDANCE ============
export const mockCareerGuides: CMSCareerGuide[] = [
  {
    id: 'career-1',
    title: 'Career Options After 12th Science',
    titleHindi: '12वीं साइंस के बाद करियर विकल्प',
    slug: 'career-after-12th-science',
    category: 'after-12th',
    description: 'Complete guide for science students after 12th',
    descriptionHindi: '12वीं के बाद साइंस छात्रों के लिए संपूर्ण गाइड',
    content: 'Detailed career paths for science students...',
    contentHindi: 'साइंस छात्रों के लिए विस्तृत करियर पथ...',
    image: '/placeholder.svg',
    author: 'Dr. Rajesh Kumar',
    authorHindi: 'डॉ. राजेश कुमार',
    eligibility: ['12th Science with PCM/PCB', 'Minimum 50% marks'],
    careerPaths: ['Engineering', 'Medical', 'BSc', 'BCA', 'Agriculture'],
    careerPathsHindi: ['इंजीनियरिंग', 'मेडिकल', 'बीएससी', 'बीसीए', 'कृषि'],
    averageSalary: '₹4-15 LPA',
    topColleges: ['IIT', 'AIIMS', 'NIT', 'BITS'],
    requiredExams: ['JEE Main', 'NEET', 'CUET'],
    isFeatured: true,
    isPopular: true,
    publishedAt: '2025-12-01',
  },
  {
    id: 'career-2',
    title: 'Government Jobs in UP 2026',
    titleHindi: 'यूपी में सरकारी नौकरियां 2026',
    slug: 'government-jobs-up-2026',
    category: 'government-jobs',
    description: 'All upcoming government jobs in UP',
    descriptionHindi: 'यूपी में सभी आगामी सरकारी नौकरियां',
    content: 'Complete list of government job opportunities...',
    contentHindi: 'सरकारी नौकरी के अवसरों की पूरी सूची...',
    author: 'Career Expert',
    authorHindi: 'करियर विशेषज्ञ',
    careerPaths: ['UP Police', 'Lekhpal', 'Teacher', 'Clerk'],
    averageSalary: '₹25,000 - ₹1,50,000/month',
    requiredExams: ['UPSSSC PET', 'UP Police', 'UPTET'],
    isFeatured: true,
    publishedAt: '2025-12-15',
  },
  {
    id: 'career-3',
    title: 'Career in Teaching',
    titleHindi: 'शिक्षण में करियर',
    slug: 'career-in-teaching',
    category: 'government-jobs',
    description: 'How to become a teacher in India',
    descriptionHindi: 'भारत में शिक्षक कैसे बनें',
    content: 'Step by step guide to become a teacher...',
    contentHindi: 'शिक्षक बनने के लिए चरणबद्ध गाइड...',
    eligibility: ['Graduation', 'B.Ed/D.El.Ed', 'CTET/TET Qualified'],
    careerPaths: ['Primary Teacher', 'TGT', 'PGT', 'Lecturer'],
    averageSalary: '₹35,000 - ₹1,00,000/month',
    requiredExams: ['CTET', 'UPTET', 'Super TET'],
    isFeatured: true,
    publishedAt: '2025-11-20',
  },
];

// ============ EDUCATION NEWS ============
export const mockEducationNews: CMSEducationNews[] = [
  {
    id: 'news-1',
    title: 'UP Board Exam 2026 Date Sheet Released',
    titleHindi: 'यूपी बोर्ड परीक्षा 2026 की डेट शीट जारी',
    slug: 'up-board-exam-2026-date-sheet',
    category: 'exam-news',
    excerpt: 'UP Board has released the date sheet for Class 10 and 12 exams 2026',
    excerptHindi: 'यूपी बोर्ड ने कक्षा 10 और 12 की परीक्षा 2026 की डेट शीट जारी की',
    content: 'The Uttar Pradesh Madhyamik Shiksha Parishad has released...',
    contentHindi: 'उत्तर प्रदेश माध्यमिक शिक्षा परिषद ने...',
    image: '/placeholder.svg',
    isBreaking: true,
    isImportant: true,
    isFeatured: true,
    publishedAt: '2026-01-02',
    relatedExams: ['exam-1', 'exam-2'],
    tags: ['UP Board', 'Date Sheet', 'Exam 2026'],
  },
  {
    id: 'news-2',
    title: 'UPTET 2026 Application Extended',
    titleHindi: 'यूपीटीईटी 2026 आवेदन की अंतिम तिथि बढ़ी',
    slug: 'uptet-2026-application-extended',
    category: 'exam-news',
    excerpt: 'UPTET application deadline extended to December 20',
    excerptHindi: 'यूपीटीईटी आवेदन की अंतिम तिथि 20 दिसंबर तक बढ़ी',
    content: 'The UP Basic Education Board has extended...',
    contentHindi: 'उत्तर प्रदेश बेसिक शिक्षा परिषद ने...',
    isImportant: true,
    publishedAt: '2025-12-28',
    relatedExams: ['exam-3'],
    tags: ['UPTET', 'Application', 'Extended'],
  },
  {
    id: 'news-3',
    title: 'Free Coaching for SC/ST Students',
    titleHindi: 'एससी/एसटी छात्रों के लिए मुफ्त कोचिंग योजना',
    slug: 'free-coaching-sc-st-students',
    category: 'scholarship',
    excerpt: 'Government announces free coaching scheme for SC/ST students',
    excerptHindi: 'सरकार ने एससी/एसटी छात्रों के लिए मुफ्त कोचिंग योजना की घोषणा की',
    content: 'Under the new scheme, eligible students will receive...',
    contentHindi: 'नई योजना के तहत, पात्र छात्रों को मिलेगी...',
    isImportant: true,
    isFeatured: true,
    publishedAt: '2025-12-25',
    tags: ['Scholarship', 'Free Coaching', 'SC/ST'],
  },
  {
    id: 'news-4',
    title: 'UP Police SI Result 2025 Expected Soon',
    titleHindi: 'यूपी पुलिस एसआई रिजल्ट 2025 जल्द आने की संभावना',
    slug: 'up-police-si-result-2025-expected',
    category: 'result-news',
    excerpt: 'UP Police SI Result 2025 likely to be declared by mid-January',
    excerptHindi: 'यूपी पुलिस एसआई रिजल्ट 2025 जनवरी मध्य तक घोषित होने की संभावना',
    content: 'The UP Police Recruitment Board is expected to release...',
    contentHindi: 'उत्तर प्रदेश पुलिस भर्ती बोर्ड द्वारा...',
    isBreaking: true,
    publishedAt: '2026-01-01',
    tags: ['UP Police', 'SI Result', 'Expected'],
  },
  {
    id: 'news-5',
    title: 'Post Matric Scholarship 2026 Applications Open',
    titleHindi: 'पोस्ट मैट्रिक छात्रवृत्ति 2026 आवेदन शुरू',
    slug: 'post-matric-scholarship-2026-open',
    category: 'scholarship',
    excerpt: 'Apply now for Post Matric Scholarship Scheme 2026',
    excerptHindi: 'पोस्ट मैट्रिक छात्रवृत्ति योजना 2026 के लिए अभी आवेदन करें',
    content: 'The UP government has opened applications for...',
    contentHindi: 'उत्तर प्रदेश सरकार ने आवेदन शुरू किए...',
    isImportant: true,
    publishedAt: '2025-12-20',
    tags: ['Scholarship', 'Post Matric', 'UP'],
  },
  {
    id: 'news-6',
    title: 'CBSE Class 12 Practical Exam Dates Announced',
    titleHindi: 'सीबीएसई कक्षा 12 प्रैक्टिकल परीक्षा तिथियां घोषित',
    slug: 'cbse-class-12-practical-dates',
    category: 'board-news',
    excerpt: 'CBSE announces practical exam schedule for Class 12',
    excerptHindi: 'सीबीएसई ने कक्षा 12 के लिए प्रैक्टिकल परीक्षा शेड्यूल घोषित किया',
    content: 'The Central Board of Secondary Education has...',
    contentHindi: 'केंद्रीय माध्यमिक शिक्षा बोर्ड ने...',
    publishedAt: '2025-12-18',
    tags: ['CBSE', 'Practical Exam', 'Class 12'],
  },
  {
    id: 'news-7',
    title: 'National Means-cum-Merit Scholarship Results',
    titleHindi: 'राष्ट्रीय साधन-सह-मेरिट छात्रवृत्ति परिणाम',
    slug: 'nmms-scholarship-results-2025',
    category: 'scholarship',
    excerpt: 'NMMS Scholarship results declared for UP students',
    excerptHindi: 'यूपी छात्रों के लिए एनएमएमएस छात्रवृत्ति परिणाम घोषित',
    content: 'The National Means-cum-Merit Scholarship results...',
    contentHindi: 'राष्ट्रीय साधन-सह-मेरिट छात्रवृत्ति परिणाम...',
    publishedAt: '2025-12-15',
    tags: ['NMMS', 'Scholarship', 'Results'],
  },
  {
    id: 'news-8',
    title: 'UP Board Changes Exam Pattern for 2026',
    titleHindi: 'यूपी बोर्ड ने 2026 के लिए परीक्षा पैटर्न बदला',
    slug: 'up-board-exam-pattern-change-2026',
    category: 'board-news',
    excerpt: 'Major changes in UP Board exam pattern for session 2025-26',
    excerptHindi: 'सत्र 2025-26 के लिए यूपी बोर्ड परीक्षा पैटर्न में बड़े बदलाव',
    content: 'The UP Board has introduced significant changes...',
    contentHindi: 'यूपी बोर्ड ने महत्वपूर्ण बदलाव किए हैं...',
    isImportant: true,
    publishedAt: '2025-12-10',
    tags: ['UP Board', 'Exam Pattern', 'Changes'],
  },
  {
    id: 'news-9',
    title: 'Government Orders Free Textbooks for UP Students',
    titleHindi: 'सरकार ने यूपी छात्रों के लिए मुफ्त पाठ्यपुस्तकें देने का आदेश दिया',
    slug: 'free-textbooks-up-students-2026',
    category: 'government-order',
    excerpt: 'All government school students to receive free textbooks',
    excerptHindi: 'सभी सरकारी स्कूल के छात्रों को मुफ्त पाठ्यपुस्तकें मिलेंगी',
    content: 'The UP government has ordered...',
    contentHindi: 'उत्तर प्रदेश सरकार ने आदेश दिया है...',
    publishedAt: '2025-12-05',
    tags: ['Free Textbooks', 'Government Order', 'UP'],
  },
  {
    id: 'news-10',
    title: 'JEE Main 2026 Session 1 Admit Cards Soon',
    titleHindi: 'जेईई मेन 2026 सत्र 1 एडमिट कार्ड जल्द',
    slug: 'jee-main-2026-session-1-admit-card',
    category: 'admission-news',
    excerpt: 'JEE Main Session 1 admit cards expected by January 10',
    excerptHindi: 'जेईई मेन सत्र 1 एडमिट कार्ड 10 जनवरी तक आने की उम्मीद',
    content: 'The National Testing Agency is expected to...',
    contentHindi: 'नेशनल टेस्टिंग एजेंसी द्वारा...',
    publishedAt: '2026-01-02',
    tags: ['JEE Main', 'Admit Card', 'NTA'],
  },
];

// ============ EDUCATION EVENTS ============
export const mockEducationEvents: CMSEducationEvent[] = [
  {
    id: 'edu-event-1',
    title: 'Career Counseling Webinar',
    titleHindi: 'करियर काउंसलिंग वेबिनार',
    slug: 'career-counseling-webinar-jan-2026',
    type: 'webinar',
    date: '2026-01-15',
    time: '4:00 PM',
    venue: 'Online',
    venueHindi: 'ऑनलाइन',
    venueType: 'online',
    registrationLink: 'https://example.com/register',
    description: 'Free career counseling session for students',
    descriptionHindi: 'छात्रों के लिए मुफ्त करियर काउंसलिंग सत्र',
    organizer: 'Rampur Education Hub',
    organizerHindi: 'रामपुर एजुकेशन हब',
    isFree: true,
    status: 'upcoming',
    isFeatured: true,
  },
  {
    id: 'edu-event-2',
    title: 'UP Board Exam Preparation Workshop',
    titleHindi: 'यूपी बोर्ड परीक्षा तैयारी कार्यशाला',
    slug: 'up-board-exam-prep-workshop',
    type: 'workshop',
    date: '2026-01-20',
    time: '10:00 AM',
    venue: 'Government Inter College, Rampur',
    venueHindi: 'राजकीय इंटर कॉलेज, रामपुर',
    venueType: 'offline',
    description: 'One-day workshop for UP Board students',
    descriptionHindi: 'यूपी बोर्ड छात्रों के लिए एक दिवसीय कार्यशाला',
    isFree: true,
    status: 'upcoming',
    isFeatured: true,
  },
];

// ============ TESTIMONIALS ============
export const mockTestimonials: CMSTestimonial[] = [
  {
    id: 'test-1',
    name: 'Ankit Sharma',
    nameHindi: 'अंकित शर्मा',
    designation: 'UP Police Constable',
    designationHindi: 'यूपी पुलिस कांस्टेबल',
    image: '/placeholder.svg',
    content: 'The exam calendar and study resources helped me prepare systematically. I cleared UP Police exam in my first attempt.',
    contentHindi: 'परीक्षा कैलेंडर और अध्ययन संसाधनों ने मुझे व्यवस्थित तैयारी में मदद की। मैंने पहले प्रयास में यूपी पुलिस परीक्षा पास की।',
    rating: 5,
    exam: 'UP Police',
    year: '2025',
    isFeatured: true,
  },
  {
    id: 'test-2',
    name: 'Priya Singh',
    nameHindi: 'प्रिया सिंह',
    designation: 'Primary Teacher',
    designationHindi: 'प्राथमिक शिक्षक',
    image: '/placeholder.svg',
    content: 'Thanks to the career guidance section, I chose the right path. Now I am a government teacher.',
    contentHindi: 'करियर गाइडेंस सेक्शन की बदौलत मैंने सही रास्ता चुना। अब मैं सरकारी शिक्षक हूं।',
    rating: 5,
    exam: 'UPTET',
    year: '2024',
    isFeatured: true,
  },
];

// ============ EXPERTS ============
export const mockExperts: CMSExpert[] = [
  {
    id: 'expert-1',
    name: 'Dr. Rajesh Kumar',
    nameHindi: 'डॉ. राजेश कुमार',
    designation: 'Career Counselor',
    designationHindi: 'करियर काउंसलर',
    specialization: 'Government Jobs',
    specializationHindi: 'सरकारी नौकरियां',
    image: '/placeholder.svg',
    bio: 'Expert in government job preparation with 15+ years of experience.',
    bioHindi: '15+ वर्षों के अनुभव के साथ सरकारी नौकरी तैयारी में विशेषज्ञ।',
    experience: 15,
    education: 'Ph.D. Education',
    socialLinks: {
      youtube: 'https://youtube.com',
    },
    isFeatured: true,
  },
  {
    id: 'expert-2',
    name: 'Neha Verma',
    nameHindi: 'नेहा वर्मा',
    designation: 'Education Consultant',
    designationHindi: 'शिक्षा सलाहकार',
    specialization: 'Board Exams',
    specializationHindi: 'बोर्ड परीक्षाएं',
    image: '/placeholder.svg',
    bio: 'Helping students excel in board exams for over a decade.',
    bioHindi: 'एक दशक से अधिक समय से छात्रों को बोर्ड परीक्षाओं में उत्कृष्टता प्राप्त करने में मदद।',
    experience: 12,
    isFeatured: true,
  },
];

// ============ VIDEO TUTORIALS ============
export const mockVideoTutorials: CMSVideoTutorial[] = [
  {
    id: 'video-1',
    title: 'How to Prepare for UP Board 2026',
    titleHindi: 'यूपी बोर्ड 2026 की तैयारी कैसे करें',
    slug: 'how-to-prepare-up-board-2026',
    category: 'exam-prep',
    description: 'Complete preparation strategy for UP Board exams',
    descriptionHindi: 'यूपी बोर्ड परीक्षाओं के लिए संपूर्ण तैयारी रणनीति',
    thumbnailUrl: '/placeholder.svg',
    videoUrl: 'https://youtube.com/watch?v=example',
    duration: '25:30',
    views: 15000,
    instructor: 'Dr. Rajesh Kumar',
    instructorHindi: 'डॉ. राजेश कुमार',
    tags: ['UP Board', 'Preparation', 'Strategy'],
    isFeatured: true,
    publishedAt: '2025-12-01',
  },
  {
    id: 'video-2',
    title: 'SSC GD Preparation Tips',
    titleHindi: 'एसएससी जीडी तैयारी टिप्स',
    slug: 'ssc-gd-preparation-tips',
    category: 'exam-prep',
    description: 'Expert tips for SSC GD Constable exam',
    descriptionHindi: 'एसएससी जीडी कांस्टेबल परीक्षा के लिए विशेषज्ञ टिप्स',
    thumbnailUrl: '/placeholder.svg',
    videoUrl: 'https://youtube.com/watch?v=example2',
    duration: '32:15',
    views: 28000,
    tags: ['SSC GD', 'Tips', 'Preparation'],
    isFeatured: true,
    publishedAt: '2025-11-15',
  },
];

// ============ CULTURE: HOLIDAYS ============
export const mockHolidays: CMSHoliday[] = [
  {
    id: 'holiday-1',
    name: 'Republic Day',
    nameHindi: 'गणतंत्र दिवस',
    slug: 'republic-day',
    date: '2026-01-26',
    type: 'national',
    description: 'India celebrates its Republic Day on January 26th.',
    descriptionHindi: 'भारत 26 जनवरी को अपना गणतंत्र दिवस मनाता है।',
    significance: 'The day India became a republic in 1950.',
    significanceHindi: 'वह दिन जब भारत 1950 में गणतंत्र बना।',
    isRecurring: true,
    recurringType: 'yearly',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-2',
    name: 'Holi',
    nameHindi: 'होली',
    slug: 'holi',
    date: '2026-03-04',
    type: 'religious',
    religion: 'hindu',
    description: 'Festival of colors celebrating the victory of good over evil.',
    descriptionHindi: 'रंगों का त्योहार जो बुराई पर अच्छाई की जीत का जश्न मनाता है।',
    significance: 'Celebrates the divine love of Radha Krishna and victory of Prahlad.',
    rituals: ['Playing with colors', 'Holika Dahan', 'Gujiya preparation'],
    ritualsHindi: ['रंगों से खेलना', 'होलिका दहन', 'गुझिया बनाना'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-3',
    name: 'Eid ul-Fitr',
    nameHindi: 'ईद उल-फ़ित्र',
    slug: 'eid-ul-fitr',
    date: '2026-03-21',
    type: 'religious',
    religion: 'muslim',
    description: 'Festival marking the end of Ramadan.',
    descriptionHindi: 'रमज़ान के समापन का पर्व।',
    significance: 'Celebrates the end of month-long fasting.',
    rituals: ['Eid prayers', 'Giving Zakat', 'Family gatherings', 'Feasting'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-4',
    name: 'Independence Day',
    nameHindi: 'स्वतंत्रता दिवस',
    slug: 'independence-day',
    date: '2026-08-15',
    type: 'national',
    description: 'India celebrates its independence from British rule.',
    descriptionHindi: 'भारत ब्रिटिश शासन से अपनी स्वतंत्रता का जश्न मनाता है।',
    significance: 'India gained independence on August 15, 1947.',
    isRecurring: true,
    recurringType: 'yearly',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-5',
    name: 'Diwali',
    nameHindi: 'दिवाली',
    slug: 'diwali',
    date: '2026-10-20',
    endDate: '2026-10-24',
    type: 'religious',
    religion: 'hindu',
    description: 'Festival of lights celebrating the victory of light over darkness.',
    descriptionHindi: 'रोशनी का त्योहार जो अंधकार पर प्रकाश की जीत का जश्न मनाता है।',
    significance: 'Celebrates Lord Rama\'s return to Ayodhya.',
    rituals: ['Lighting diyas', 'Lakshmi Puja', 'Fireworks', 'Rangoli'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-6',
    name: 'Eid ul-Adha',
    nameHindi: 'ईद उल-अज़हा',
    slug: 'eid-ul-adha',
    date: '2026-05-27',
    type: 'religious',
    religion: 'muslim',
    description: 'Festival of Sacrifice.',
    descriptionHindi: 'कुर्बानी का त्योहार।',
    significance: 'Commemorates Ibrahim\'s willingness to sacrifice his son.',
    rituals: ['Eid prayers', 'Qurbani', 'Charity', 'Family gatherings'],
    isRecurring: true,
    recurringType: 'lunar',
    isPublicHoliday: true,
  },
  {
    id: 'holiday-7',
    name: 'Gandhi Jayanti',
    nameHindi: 'गांधी जयंती',
    slug: 'gandhi-jayanti',
    date: '2026-10-02',
    type: 'national',
    description: 'Birthday of Mahatma Gandhi.',
    descriptionHindi: 'महात्मा गांधी का जन्मदिन।',
    significance: 'Celebrates the Father of the Nation.',
    isRecurring: true,
    recurringType: 'yearly',
    isPublicHoliday: true,
  },
];

// ============ FOOD & LIFESTYLE: RESTAURANTS ============
export const mockRestaurants: CMSRestaurant[] = [
  {
    id: 'rest-1',
    name: 'Sharma Ji Ka Dhaba',
    nameHindi: 'शर्मा जी का ढाबा',
    slug: 'sharma-ji-ka-dhaba',
    type: 'dhaba',
    cuisine: ['North Indian', 'Mughlai'],
    address: 'Civil Lines, Rampur',
    addressHindi: 'सिविल लाइंस, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543210',
    priceRange: 'budget',
    rating: 4.3,
    reviews: 234,
    openingHours: '7:00 AM - 11:00 PM',
    specialties: ['Dal Makhani', 'Butter Chicken', 'Tandoori Roti'],
    specialtiesHindi: ['दाल मखनी', 'बटर चिकन', 'तंदूरी रोटी'],
    description: 'Famous dhaba known for authentic North Indian cuisine.',
    descriptionHindi: 'प्रामाणिक उत्तर भारतीय व्यंजनों के लिए प्रसिद्ध ढाबा।',
    isVeg: false,
    hasDelivery: true,
    isFeatured: true,
  },
  {
    id: 'rest-2',
    name: 'Rampur Sweet House',
    nameHindi: 'रामपुर स्वीट हाउस',
    slug: 'rampur-sweet-house',
    type: 'sweet-shop',
    cuisine: ['Sweets', 'Snacks'],
    address: 'Naya Ganj, Rampur',
    addressHindi: 'नया गंज, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543211',
    priceRange: 'moderate',
    rating: 4.6,
    reviews: 456,
    openingHours: '8:00 AM - 10:00 PM',
    specialties: ['Gulab Jamun', 'Jalebi', 'Samosa', 'Kachori'],
    description: 'Traditional sweet shop serving authentic Rampur sweets.',
    descriptionHindi: 'पारंपरिक मिठाई की दुकान जो प्रामाणिक रामपुरी मिठाइयाँ परोसती है।',
    isVeg: true,
    hasDelivery: true,
    isFeatured: true,
  },
  {
    id: 'rest-3',
    name: 'Royal Biryani House',
    nameHindi: 'रॉयल बिरयानी हाउस',
    slug: 'royal-biryani-house',
    type: 'restaurant',
    cuisine: ['Mughlai', 'Biryani'],
    address: 'Shahbad Gate, Rampur',
    addressHindi: 'शाहबाद गेट, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543212',
    priceRange: 'moderate',
    rating: 4.4,
    reviews: 312,
    openingHours: '11:00 AM - 11:00 PM',
    specialties: ['Mutton Biryani', 'Chicken Biryani', 'Kebabs'],
    description: 'Famous for Nawabi style biryani and kebabs.',
    descriptionHindi: 'नवाबी स्टाइल बिरयानी और कबाब के लिए प्रसिद्ध।',
    isVeg: false,
    hasDelivery: true,
    isFeatured: true,
  },
];

// ============ FOOD & LIFESTYLE: FASHION STORES ============
export const mockFashionStores: CMSFashionStore[] = [
  {
    id: 'fashion-1',
    name: 'Rampur Saree Emporium',
    nameHindi: 'रामपुर साड़ी एम्पोरियम',
    slug: 'rampur-saree-emporium',
    type: 'clothing',
    category: 'women',
    address: 'Main Market, Rampur',
    addressHindi: 'मुख्य बाजार, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543220',
    priceRange: 'moderate',
    rating: 4.5,
    specialties: ['Banarasi Sarees', 'Chikankari', 'Bridal Collection'],
    specialtiesHindi: ['बनारसी साड़ी', 'चिकनकारी', 'ब्राइडल कलेक्शन'],
    description: 'Premium saree collection for all occasions.',
    descriptionHindi: 'सभी अवसरों के लिए प्रीमियम साड़ी संग्रह।',
    isFeatured: true,
  },
  {
    id: 'fashion-2',
    name: 'Style Junction',
    nameHindi: 'स्टाइल जंक्शन',
    slug: 'style-junction',
    type: 'clothing',
    category: 'all',
    address: 'Civil Lines, Rampur',
    addressHindi: 'सिविल लाइंस, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '9876543221',
    priceRange: 'moderate',
    rating: 4.2,
    brands: ['Van Heusen', 'Peter England', 'Allen Solly'],
    description: 'Branded clothing for men and women.',
    descriptionHindi: 'पुरुषों और महिलाओं के लिए ब्रांडेड कपड़े।',
    isFeatured: true,
  },
];

// ============ FOOD & LIFESTYLE: SHOPPING CENTRES ============
export const mockShoppingCentres: CMSShoppingCentre[] = [
  {
    id: 'shop-1',
    name: 'Rampur City Mall',
    nameHindi: 'रामपुर सिटी मॉल',
    slug: 'rampur-city-mall',
    type: 'mall',
    address: 'Bareilly Road, Rampur',
    addressHindi: 'बरेली रोड, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    phone: '0595-2350100',
    openingHours: '10:00 AM - 10:00 PM',
    storeCount: 50,
    amenities: ['Food Court', 'Cinema', 'Parking', 'Kids Zone'],
    amenitiesHindi: ['फूड कोर्ट', 'सिनेमा', 'पार्किंग', 'किड्स जोन'],
    parkingAvailable: true,
    description: 'Modern shopping mall with entertainment facilities.',
    descriptionHindi: 'मनोरंजन सुविधाओं के साथ आधुनिक शॉपिंग मॉल।',
    isFeatured: true,
  },
  {
    id: 'shop-2',
    name: 'Raza Market',
    nameHindi: 'रज़ा मार्केट',
    slug: 'raza-market',
    type: 'market',
    address: 'City Center, Rampur',
    addressHindi: 'सिटी सेंटर, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    openingHours: '9:00 AM - 9:00 PM',
    storeCount: 200,
    amenities: ['Variety Shops', 'Street Food'],
    description: 'Traditional market with variety of shops.',
    descriptionHindi: 'विभिन्न दुकानों के साथ पारंपरिक बाजार।',
    isFeatured: true,
  },
];

// ============ FOOD & LIFESTYLE: FAMOUS PLACES ============
export const mockFamousPlaces: CMSFamousPlace[] = [
  {
    id: 'place-1',
    name: 'Rampur Raza Library',
    nameHindi: 'रामपुर रज़ा पुस्तकालय',
    slug: 'rampur-raza-library',
    type: 'historical',
    address: 'Fort Road, Rampur',
    addressHindi: 'किला रोड, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    description: 'Historic library with rare manuscripts and artifacts.',
    descriptionHindi: 'दुर्लभ पांडुलिपियों और कलाकृतियों के साथ ऐतिहासिक पुस्तकालय।',
    history: 'Founded by Nawab Faizullah Khan in 1774.',
    historyHindi: '1774 में नवाब फैजुल्लाह खान द्वारा स्थापित।',
    timings: '10:00 AM - 5:00 PM (Closed on Monday)',
    entryFee: 'Free',
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: 'place-2',
    name: 'Jama Masjid Rampur',
    nameHindi: 'जामा मस्जिद रामपुर',
    slug: 'jama-masjid-rampur',
    type: 'religious',
    address: 'Old City, Rampur',
    addressHindi: 'पुराना शहर, रामपुर',
    city: 'रामपुर',
    district: 'रामपुर',
    description: 'Historic mosque with beautiful architecture.',
    descriptionHindi: 'सुंदर वास्तुकला के साथ ऐतिहासिक मस्जिद।',
    timings: 'Open for prayers',
    isFeatured: true,
    rating: 4.6,
  },
];

// ============ EVENTS ============
export const mockEvents: CMSEvent[] = [
  {
    id: 'event-1',
    title: 'Rampur Food Festival 2026',
    titleHindi: 'रामपुर फूड फेस्टिवल 2026',
    slug: 'rampur-food-festival-2026',
    date: '2026-02-15',
    endDate: '2026-02-17',
    time: '11:00 AM onwards',
    venue: 'Gandhi Park',
    venueHindi: 'गांधी पार्क',
    address: 'Civil Lines, Rampur',
    city: 'रामपुर',
    district: 'रामपुर',
    category: 'food',
    organizer: 'Rampur Municipal Corporation',
    organizerHindi: 'रामपुर नगर निगम',
    description: 'Annual food festival featuring local cuisines.',
    descriptionHindi: 'स्थानीय व्यंजनों की विशेषता वाला वार्षिक खाद्य महोत्सव।',
    isFree: true,
    isFeatured: true,
    status: 'upcoming',
  },
  {
    id: 'event-2',
    title: 'Rampur Literary Festival',
    titleHindi: 'रामपुर साहित्य महोत्सव',
    slug: 'rampur-literary-festival-2026',
    date: '2026-03-01',
    endDate: '2026-03-03',
    venue: 'Raza Library',
    venueHindi: 'रज़ा पुस्तकालय',
    address: 'Fort Road, Rampur',
    city: 'रामपुर',
    district: 'रामपुर',
    category: 'cultural',
    description: 'Literary festival celebrating Urdu and Hindi literature.',
    descriptionHindi: 'उर्दू और हिंदी साहित्य का जश्न मनाने वाला साहित्यिक महोत्सव।',
    isFree: true,
    isFeatured: true,
    status: 'upcoming',
  },
];